apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-platform

resources:
  - ../../base

# Override images to use local registry
images:
  - name: localhost:5001/custom-flink
    newName: 10.152.183.69:5000/custom-flink
    newTag: latest
  - name: localhost:5001/custom-spark
    newName: 10.152.183.69:5000/custom-spark
    newTag: latest