apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: ecommerce-platform
data:
  # Only keep logging configuration here; core Flink config will be injected via FLINK_PROPERTIES env var
  log4j-console.properties: |
    log4j.rootLogger=INFO, console
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.layout=org.apache.log4j.PatternLayout
    log4j.appender.console.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: ecommerce-platform
spec:
  selector:
    app: flink
    component: jobmanager
  ports:
    - name: rpc
      port: 6123
      targetPort: 6123
    - name: web-ui
      port: 8081
      targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: flink-taskmanager
  namespace: ecommerce-platform
spec:
  selector:
    app: flink
    component: taskmanager
  ports:
    - name: data
      port: 6121
      targetPort: 6121
    - name: rpc
      port: 6122
      targetPort: 6122
    - name: query
      port: 6125
      targetPort: 6125
  clusterIP: None  # Headless service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: ecommerce-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: flink-jobmanager
        image: flink:1.18-scala_2.12
        args: ["jobmanager"]
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
        - name: FLINK_PROPERTIES
          value: |-
            jobmanager.rpc.address: flink-jobmanager
            jobmanager.rpc.port: 6123
            taskmanager.rpc.port: 6122
            data.port: 6121
            taskmanager.numberOfTaskSlots: 2
            parallelism.default: 2
            jobmanager.memory.process.size: 1600m
            taskmanager.memory.process.size: 1728m
            taskmanager.memory.flink.size: 1280m
            execution.checkpointing.interval: 10s
            execution.checkpointing.mode: EXACTLY_ONCE
            state.backend: rocksdb
            state.checkpoints.dir: file:///tmp/flink-checkpoints
            kubernetes.cluster-id: flink-cluster
            kubernetes.taskmanager.service-account: default
            s3.endpoint: http://minio:9000
            s3.path-style-access: true
            s3.ssl.enabled: false
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 8081
          name: web-ui
        volumeMounts:
        - name: flink-config
          mountPath: /opt/flink/conf/log4j-console.properties
          subPath: log4j-console.properties
        - name: apps
          mountPath: /apps
        - name: data
          mountPath: /data
        - name: flink-jars
          mountPath: /flink-jars
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: flink-config
        configMap:
          name: flink-config
      - name: apps
        configMap:
          name: flink-apps
          defaultMode: 0755
      - name: data
        emptyDir: {}
      - name: flink-jars
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: ecommerce-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: flink-taskmanager
        image: flink:1.18-scala_2.12
        args: ["taskmanager"]
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
        - name: FLINK_PROPERTIES
          value: |-
            jobmanager.rpc.address: flink-jobmanager
            jobmanager.rpc.port: 6123
            taskmanager.rpc.port: 6122
            data.port: 6121
            taskmanager.numberOfTaskSlots: 2
            parallelism.default: 2
            jobmanager.memory.process.size: 1600m
            taskmanager.memory.process.size: 1728m
            taskmanager.memory.flink.size: 1280m
            execution.checkpointing.interval: 10s
            execution.checkpointing.mode: EXACTLY_ONCE
            state.backend: rocksdb
            state.checkpoints.dir: file:///tmp/flink-checkpoints
            kubernetes.cluster-id: flink-cluster
            kubernetes.taskmanager.service-account: default
            s3.endpoint: http://minio:9000
            s3.path-style-access: true
            s3.ssl.enabled: false
        ports:
        - containerPort: 6121
          name: data
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query
        volumeMounts:
        - name: flink-config
          mountPath: /opt/flink/conf/log4j-console.properties
          subPath: log4j-console.properties
        - name: apps
          mountPath: /apps
        - name: data
          mountPath: /data
        - name: flink-jars
          mountPath: /flink-jars
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 3Gi
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 25
          periodSeconds: 10
          failureThreshold: 6
      volumes:
      - name: flink-config
        configMap:
          name: flink-config
      - name: apps
        configMap:
          name: flink-apps
          defaultMode: 0755
      - name: data
        emptyDir: {}
      - name: flink-jars
        emptyDir: {}
