apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nessie-pvc
  namespace: ecommerce-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nessie
  namespace: ecommerce-platform
spec:
  selector:
    app: nessie
  ports:
    - name: api
      port: 19120
      targetPort: 19120
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
  namespace: ecommerce-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
      - name: nessie
        image: ghcr.io/projectnessie/nessie:0.77.1
        env:
        - name: NESSIE_VERSION_STORE_TYPE
          value: "ROCKSDB"
        - name: NESSIE_VERSION_STORE_PERSIST
          value: "true"
        - name: NESSIE_VERSION_STORE_ROCKSDB_PATH
          value: "/nessie"
        ports:
        - containerPort: 19120
          name: api
        volumeMounts:
        - name: data
          mountPath: /nessie
        livenessProbe:
          httpGet:
            path: /api/v1/config
            port: 19120
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/config
            port: 19120
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nessie-pvc