FROM rayproject/ray:2.8.0-py39

# Copy application files
COPY ray-apps /apps

# Install dependencies from requirements.txt
RUN pip install -r /apps/requirements.txt

# Expose ports for Ray Dashboard, Client, and GCS
EXPOSE 8265 10001 6379
