# No 'version' tag needed for modern Docker Compose
services:
  # S3 compatible object storage
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Iceberg Catalog - Image path updated to GitHub Container Registry (ghcr.io)
  nessie:
    image: ghcr.io/projectnessie/nessie:0.77.1
    ports:
      - "19120:19120"

  # Spark Cluster
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ../data:/data
      - ../spark-apps:/apps
    command: ["sh", "-c", "/opt/spark/sbin/start-master.sh && tail -f /dev/null"]
  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=worker
    volumes:
      - ../data:/data
      - ../spark-apps:/apps
    depends_on:
      - spark-master
    command: ["sh", "-c", "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]

  # Flink Cluster
  flink-jobmanager:
    image: flink:1.18-scala_2.12
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
  flink-taskmanager:
    image: flink:1.18-scala_2.12
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2

  # Ray Cluster
  ray-head:
    # Corrected the image path from 'ray-project/ray-ml' to 'rayproject/ray-ml'
    image: rayproject/ray-ml:latest-cpu
    shm_size: '2gb'
    ports:
      - "8265:8265" # Ray Dashboard
      - "10001:10001" # Ray Client
      - "6379:6379" # Ray head port
    command: bash -c "ray start --head --port=6379 --dashboard-host=0.0.0.0 --disable-usage-stats && tail -f /dev/null"