services:
  # S3 compatible object storage
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ../data/minio:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Iceberg Catalog
  nessie:
    image: ghcr.io/projectnessie/nessie:0.77.1
    ports:
      - "19120:19120"
    environment:
      - NESSIE_VERSION_STORE_TYPE=ROCKSDB
      - NESSIE_VERSION_STORE_PERSIST=true
      - NESSIE_VERSION_STORE_ROCKSDB_PATH=/nessie
    volumes:
      - ../data/nessie:/nessie

  # Spark Cluster
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=master
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - ../data:/data
      - ../spark-apps:/apps
    command: ["sh", "-c", "/opt/spark/sbin/start-master.sh && tail -f /dev/null"]
  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    environment:
      - SPARK_MODE=worker
    volumes:
      - ../data:/data
      - ../spark-apps:/apps
    depends_on:
      - spark-master
    command: ["sh", "-c", "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"]

  # Flink Cluster
  flink-jobmanager:
    build:
      context: ..
      dockerfile: docker/Dockerfile.flink
    ports:
      - "8081:8081"
    command: jobmanager
    depends_on:
      - minio
      - nessie
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        s3.endpoint: http://minio:9000
        s3.path-style-access: true
        s3.ssl.enabled: false
    volumes:
      - ../flink-apps:/apps
      - ../data:/data
      - ../flink-jars:/flink-jars
  flink-taskmanager:
    build:
      context: ..
      dockerfile: docker/Dockerfile.flink
    depends_on:
      - flink-jobmanager
      - minio
      - nessie
    command: taskmanager
    environment:
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        s3.endpoint: http://minio:9000
        s3.path-style-access: true
        s3.ssl.enabled: false
    volumes:
      - ../flink-apps:/apps
      - ../data:/data
      - ../flink-jars:/flink-jars